before:
  hooks:
    - go mod tidy
builds:
  - id: "logstash-exporter"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    goarm:
      - 6
      - 7

archives:
  - format: zip
    name_template: "{{ .ProjectName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}{{if .Arm}}{{.Arm}}{{end}}"
